# Generated by Django 5.1.1 on 2024-10-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('director', models.CharField(max_length=255, verbose_name='')),
                ('year', models.IntegerField(verbose_name='')),
                ('cover', models.ImageField(upload_to='movies/covers/')),
            ],
        ),
    ]
